### ISSUE TITLE
Store is not thread safe

### ISSUE THREAD

**Issue by abdyer** [rozag/kozy-redux#2]
Replacing the `ArrayList` [here in SubscribableDelegate](https://github.com/rozag/kozy-redux/blob/master/libbase/src/main/kotlin/com/github/rozag/redux/base/SubscribableDelegate.kt#L9) with a `CopyOnWriteArrayList` and queuing actions in `SubscribableStore#internalDispatch` would resolve this. We currently have a custom implementation in our project to do this, but I'm happy to send a pull request if you'd like.

**Comment by rozag** [comment]
The idea behind the kozy-redux `Store` is that it shouldn't know anything about threads. The right way to fix that is to add some kind of `DispatcherProxy` that runs the whole state update cycle on a single worker thread and notifies subscribers on the main thread. Right now it's not very convenient to implement because of several design mistakes. Maybe I'll fix that sometimes. Anyway, thanks for reaching out!
